### ISSUE TITLE
outline css

### ISSUE THREAD

**Issue by topninja** [Yuvaleros/material-ui-dropzone#145] opened 2020-04-26 19:49 UTC
When upload one file on dropdown. then shows outline below

![image](https://user-images.githubusercontent.com/47001971/80317988-06cb6c00-87d5-11ea-8988-a59c52fbb70c.png)

I checked the css :
![image](https://user-images.githubusercontent.com/47001971/80318032-47c38080-87d5-11ea-8324-9da5cc522948.png)

.MuiGrid-spacing-xs-8{
   width : calc(100% + 64px)
}

I wanna remove this css or remove black outline
so all ourline should fit the dropdownzone's zone.
how to do this?
need urgent help  :>

**Comment by mattcorner** [comment] 2020-04-27 01:13
Related: Would also like to override this :focus border colour but can't seem to work out how. Including in dropzoneClass doesnt work.

Not getting this css partial draw error though, my border is complete.

**Comment by topninja** [comment] 2020-04-27 02:16
Thanks Mattcorner.
![image](https://user-images.githubusercontent.com/47001971/80327820-4dd45400-880b-11ea-8065-457dd5977efb.png)

go to this url
https://yuvaleros.github.io/material-ui-dropzone/
and on basic usage of dropzonearea,   upload any image then shows above screen
I only remove  outline .

**Comment by mattcorner** [comment] 2020-04-27 03:37
Can replicate as suggested above. I'll split my issue into a separate thread.

**Comment by panz3r** [comment] 2020-04-27 16:51
Hi @topninja ,

Thanks for your feedback and the clear explanation.
Whilst I can't replicate the issue myself (I don't see the black border but see the `:focus` outline) it seems related to how the `Material-UI` `Grid` component works and how we integrated it for the `Preview` section.

We'll look into this as soon as possible.

**Comment by max-carroll** [comment] 2020-05-04 13:45
I also get this issue, this is on chrome on a windows machine 
![image](https://user-images.githubusercontent.com/13512675/80972087-94324000-8e15-11ea-902e-f51017ee8123.png)

I hack-fixed this for myself by passing in a container spacing of 0 to previewGridProps

    previewGridProps={{
                container: { spacing: 0}
              }}

the default spacing is 8 which I think is a bit much, I have noticed that high numbers on the mui spacing seem to have bizarre results when there's not much space

**Comment by topninja** [comment] 2020-05-04 13:47
thanks for your help.

**Comment by max-carroll** [comment] 2020-05-04 14:12
Is this really resolved, I know there's a hacky workaround at the moment that I've posted but this surely is not the ultimate soloution?

**Comment by max-carroll** [comment] 2020-05-04 15:26
Thanks topninja

**Comment by max-carroll** [comment] 2020-05-05 08:32
![image](https://user-images.githubusercontent.com/13512675/81047557-8f6f9980-8eb2-11ea-8d6c-255e881d940e.png)

this negative margin is caused by the spacing={8} prop as illustrate bellow (1), this is overriden by topninja by passing in a spacing of 0 into the container (2)

![image](https://user-images.githubusercontent.com/13512675/81047609-ae6e2b80-8eb2-11ea-88ed-f0a5a587912a.png)

According to this article here https://blog.logrocket.com/the-material-ui-grid-system/ on the mui grid system a negative margin problem can be fixed in a few ways

1. Not using the spacing feature and implementing it in userspace spacing={0} (default)
2. Applying padding to the parent with at least half the spacing value applied to the child
3. Adding overflow-x: hidden; to the parent

I will experiment with ideas 2 and 3 and report back

**Comment by max-carroll** [comment] 2020-05-05 11:19
I'm tending towards the overflow soloution, this was a oneline code change and if we do decide to change the spacing of the items perhaps this is a seperate issue such as "the spacing is too large". The overflow issue fixed the problem it appears to behaving exactly as before but with the rubber band not  misshapen, I will just make sure it works the same for more files when the files go onto a second row

**Comment by max-carroll** [comment] 2020-05-05 11:25
So with the overflow hidden set on the dropzone 

![image](https://user-images.githubusercontent.com/13512675/81061017-83dc9c80-8ecb-11ea-8c13-58684bafd0c9.png)

here is a before and after image

# Before
![image](https://user-images.githubusercontent.com/13512675/81060958-6576a100-8ecb-11ea-80c0-3b54771d57ea.png)

# After
![image](https://user-images.githubusercontent.com/13512675/81060890-4710a580-8ecb-11ea-9b3b-01105a15cfae.png)

**Comment by max-carroll** [comment] 2020-05-05 11:45
I have created a PR #156 that fixes this

**Comment by max-carroll** [comment] 2020-05-05 13:12
I have made a PR for the backport  which is here PR #157

**Closed** 2020-05-05 13:52 UTC
Labels: bug

**Comment by topninja** [comment] 2020-05-05 14:00
great   max-carroll
can you tell me your email?

**Comment by max-carroll** [comment] 2020-05-05 14:49
> great max-carroll
> can you tell me your email?

I have emailed you from my personal email address 😄

**Comment by shasu01** [comment] 2020-05-06 10:47
I am having the issue with the scroll. how do I fix it?

**Comment by max-carroll** [comment] 2020-05-06 10:53
Is that as a result of the new overflow: hidden proprerty on the dropzone? can you send a screenshot? 

If this issue is a result of the overflow hidden property can you confirm this by switching it off to double check.

![image](https://user-images.githubusercontent.com/13512675/81169044-0dee3900-8f90-11ea-8b00-e78c2793bb83.png)


![image](https://user-images.githubusercontent.com/13512675/81169031-0890ee80-8f90-11ea-8243-3edaecd99016.png)

**Comment by shasu01** [comment] 2020-05-06 11:03
this is what I get, I added in your change as 
const styles = {
      customClass: {
       overflow: 'visible'
      }
   }
const classes = useStyles();

<DropzoneArea
            dropzoneClass={classes.customClass}
            acceptedFiles={['image/*', 'application/pdf']}
            filesLimit={1}
            maxFileSize={100000}
            dropzoneText='Drag and drop an image file here or click'
            onChange={this.handleChange.bind(this)}
            showPreviewsInDropzone={true}
            fullWidth={false}
            maxWidth={'sm'}    
            showAlerts={true}
            />

![image](https://user-images.githubusercontent.com/30653592/81169846-dd130180-8f99-11ea-8100-1c8a3c9c0664.png)

**Comment by max-carroll** [comment] 2020-05-06 11:04
send me a screenshot before you changed any css please to show me what the original problem was

**Comment by shasu01** [comment] 2020-05-06 11:07
I need to get rid of the scrollbars. I added in a 
<div style={{width:'90%', height:'90%'}}>
but the vertical scroll remains and the above issue comes in

![image](https://user-images.githubusercontent.com/30653592/81170121-69252900-8f9a-11ea-81e9-84f85e3823d9.png)

**Comment by max-carroll** [comment] 2020-05-06 11:09
there shouldnt be any scroll bars, is this screenshot you just sent before any of your fixes? including the <<div style={{width:'90%', height:'90%'}}>

**Comment by max-carroll** [comment] 2020-05-06 11:12
I want to help you, but I also want to diagnose if there's any problem with this fix, and to determine if this issue needs to be reopened, a new one created, or whether there's anything strange about your code that's causing the issue. If you provide enough details as to whats going on in your situation I will help you

**Comment by shasu01** [comment] 2020-05-06 11:14
yes the last screenshot is before any changes.
this is original code
<DropzoneArea
            acceptedFiles={['image/*', 'application/pdf']}
            filesLimit={1}
            maxFileSize={100000}
            dropzoneText='Drag and drop an image file here or click'
            onChange={this.handleChange.bind(this)}
            showPreviewsInDropzone={true}
            fullWidth={false}
            maxWidth={'sm'}    
            showAlerts={true}
            />

![image](https://user-images.githubusercontent.com/30653592/81170711-6d9e1180-8f9b-11ea-9bf3-7780147de985.png)


my email address is shahistasubrati1@gmail.com

**Comment by max-carroll** [comment] 2020-05-06 11:21
I would try the following things

- Look at the containing div is there anything stange? like a max width or something
- try deleting maxWidth prop

If these 2 fail then maybe there is something wrong with this solution could you confirm by seeing if you get the same result on the example page, so we can eliminate the surrounding code as the issue

- I implemented the overflow: hidden as a soloution to this but there are other soloutions so if you think thats whats having a negative impact as a temprary workaround you can

1. set the overflow back to hidden (that will fix your scrolling issue) but you will now have the rubber band with a funny shape issue
2. you can use a work around fix for this by passing in a spacing: 0 prop into the previewList props like this
```jsx
    <DropzoneArea
    ...
    previewGridProps={{
                container: { spacing: 0}
              }}
    ...
   />
```

**Comment by shasu01** [comment] 2020-05-06 11:32
Its working!!! Thank you

<DropzoneArea
            acceptedFiles={['image/*', 'application/pdf']}
            filesLimit={1}
            maxFileSize={100000}
            dropzoneText='Drag and drop an image file here or click'
            onChange={this.handleChange.bind(this)}
            showPreviewsInDropzone={true}
            fullWidth={false}
            previewGridProps={{
              container: { spacing: 0}
            }}
            showAlerts={true}
            />

![image](https://user-images.githubusercontent.com/30653592/81172089-ddad9700-8f9d-11ea-8c73-91869378f31c.png)

**Comment by max-carroll** [comment] 2020-05-06 11:40
If you think there is an issue with the material-ui-dropzone and would like us to fix it then we need to be able to reproduce the exact same problem you had, the solution is just a hack as opposed to actually really fixing the underlying problem,

for instance it may be the container that your <DropzoneArea> is in thats the problem, we just don't know with the info you provided

**Comment by Diaver** [comment] 2020-05-10 05:39
The same issue for DropzoneDialog:
![image](https://user-images.githubusercontent.com/644716/81491670-f7313600-925e-11ea-86f1-64774d0a80e5.png)
It is fixed by:
![image](https://user-images.githubusercontent.com/644716/81491684-14fe9b00-925f-11ea-9c55-d8438bcb2f75.png)

Maybe make sense apply some permanent fix for that?
