### ISSUE TITLE
Ability to clear the list of files programmatically

### ISSUE THREAD

**Issue by IsabellaRey** [Yuvaleros/material-ui-dropzone#46] opened 2019-04-25 14:06 UTC
Following the documentation example:
```
class DropzoneAreaExample extends Component{
  constructor(props){
    super(props);
    this.state = {
      files: []
    };
  }
  handleChange(files){
    this.setState({
      files: files
    });
  }
  render(){
    return (
      <DropzoneArea 
        onChange={this.handleChange.bind(this)}
        />
    )  
  }
} 
```
I keep track of all files dropped. Then I want to do something with them, e.g. when the user clicks a Submit button I send them to the server. At this point I want to clear the list of files, because they have been processed. I can clear the files array within the state of DropzoneAreaExample  but I don't have control over the list of fileObjects internal to DropzoneArea! That list only clears on unmount!

I managed a hack by setting the key property of DropzoneArea to an incrementing counter, which triggers the unmount and re-renders as I want it but it would be nice if there was a better way to handle this.

How does everyone else do it anyway?
I suppose I could bind to onDrop instead of onChange but then I can't make good use of the preview anymore

**Comment by IsabellaRey** [comment] 2019-04-25 14:08
Duh... duplicate of #9  sorry! And it's reassuring that they've listed the same solution there!

**Comment by Yuvaleros** [comment] 2019-05-04 06:30
Duplicate of #9

**Closed by Yuvaleros** 2019-05-04 06:30 UTC
