### ISSUE TITLE
 Component modifies the file name giving an incorrect extra file extension

### ISSUE THREAD

**Issue by mballeng91** [Yuvaleros/material-ui-dropzone#135] opened 2020-04-18 02:54 UTC
Hi @Yuvaleros, thanks for this cool component

I found an issue while providing initialFiles as `initialFiles={[`https://images.pexels.com/photos/1909603/pexels-photo-1909603.jpeg`]}` Dropzone component modifies the file name giving an incorrect extra extension. This is an unexpected behaviour

![image](https://user-images.githubusercontent.com/7406472/79626440-d3fae700-80f5-11ea-9ad3-bb99bf164d4a.png)

Are you guys able to fix this issue? Thanks a lot

**Comment by mballeng91** [comment] 2020-04-23 23:17
Hi @panz3r  Today I've updated material ui dropzone to ^2.5.0 package but unfortunately issue is still presenting ...  Am I missing any configuration or something ? Thanks for your attention to this!

**Comment by panz3r** [comment] 2020-04-24 08:18
Hi @mballeng91 ,

You are right, although the changes have been merged they are yet to be published to `npm`, for now if you need to upgrade you can install the module directly from `GitHub`

for release `v3.x`
```shell
❯ npm i yuvaleros/material-ui-dropzone#d9f1c22
```
(the same also works with `yarn`)

for release `v2.x`
```shell
❯ npm i yuvaleros/material-ui-dropzone#d26e28b
```

To see the differences between the 2 version see the [CHANGELOG](https://github.com/Yuvaleros/material-ui-dropzone/blob/master/CHANGELOG.md).

Thanks for your feedback and patience.

**Comment by mballeng91** [comment] 2020-04-24 17:30
Thanks a lot!

**Comment by mballeng91** [comment] 2020-04-29 16:37
Hi @panz3r I'm afraid the version `❯ npm i yuvaleros/material-ui-dropzone#d26e28b` still presents the issue... Could you please check once again ? Thanks for your comprehension with this request

**Comment by mballeng91** [comment] 2020-04-29 17:46
Hi @panz3r  I've tried both versions you suggested me, but none of them seems to work with the fix. Could you please check once again ? Thanks for your patience with this request

**Comment by panz3r** [comment] 2020-04-30 08:07
Hi @mballeng91 ,

Thanks for your feedback. 

I'll check this once again, I think to know the cause of the issue and should be related to extensions not matching MIME types (like `jpeg` and `jpg` both matching `image/jpeg`).

Have you got an example filename that's causing you issues?

**Comment by mballeng91** [comment] 2020-04-30 14:11
Sure, whenever I try to load an image which extension is jpg... It's name is automatically changed 
![image](https://user-images.githubusercontent.com/7406472/80720305-5904d980-8ac2-11ea-9fc1-ea131c76d0a0.png)
The original file name was 'EFFECTS.jpg' but it's modified to 'EFFECTS.jpg.jpeg'

**Closed** 2020-04-30 20:26 UTC
Labels: bug

**Comment by panz3r** [comment] 2020-05-01 09:48
Hi @mballeng91 ,

Merged the fix for this issue into both `master` and `v2.x` branches.

Until published to npm, for release `v3.x` use
```shell
❯ npm i yuvaleros/material-ui-dropzone#be31b59
```
(the same also works with `yarn`)

for release `v2.x`
```shell
❯ npm i yuvaleros/material-ui-dropzone#2dab561
```

To see the differences between the 2 version see the [CHANGELOG](https://github.com/Yuvaleros/material-ui-dropzone/blob/master/CHANGELOG.md).

Thanks for your feedback and patience.

**Comment by mballen-1** [comment] 2020-06-28 02:42
The component works perfectly now (v3), Thanks a lot @panz3r
